### ISSUE TITLE
Lantern spam + mob spawners = crash/corrupt world

### ISSUE THREAD

**Issue by ghost** [Playelectro/magical-lanterns#1]
When I place around 2 warding and 2 containment lanterns near each other with 1 life lantern near a mob spawner, there's a chance that after a while, the game crashes, and every time I open the world, the game instantly crashes.

I haven't had this issue with vanilla mob spawners, only those with mods. But I noticed this with 3 different mods so far that have mob spawners, so I believe this isn't any specific mod, rather, an issue with this lantern spam and special mob spanwers in general.

These mob spawners were basic, I'm unsure if the data/nbt was different, but they were normal vanilla mobs with no armor. I'm sure it's not due to mob spam as manually spawned mobs did not have this issue. Perhaps the issue is when a mob is spawned while the lanterns are affecting mobs? I'm not sure, sorry.

**Comment by MiusR** [comment]
can you send me the crash report?

**Comment by ghost** [comment]
> 
> 
> can you send me the crash report?

Okay so somehow I crashed the server with literally just 1 containment lantern. I had a "blood moon" event, due to enhanced celetials mod. Basically, I had over 1k mobs spawn at night. Kind of confused on this.

[crash-2021-04-13_15.40.58-server.txt](https://github.com/Playelectro/magical-lanterns/files/6307062/crash-2021-04-13_15.40.58-server.txt)

**Comment by MiusR** [comment]
the crash log says line 36 is the line that causes problems.... that line of code applies the slowness effect after pull which seems to hurt the server a lot when it has to apply it to 1k mobs therefore it will be removed since it's not that important and that should stop the crash from occurring but I think I might need to rethink the purpose of the lanterns at some point since they weren't designed to interact with 1k mobs at the same time (I don't understand how your computer can handle so many >.<)
